
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-staff
owner: ucsb-cs156-s25
repo_name: team02-staff
pull_requests: [{"author":{"id":"MDQ6VXNlcjEyNTM2MTg3","is_bot":false,"login":"ameymwalimbe","name":""},"headRefName":"aw-UCSBOrgFixtures","number":122,"title":"Adding UCSB Organization fixtures [MERGE AFTER #17]","url":"https://github.com/ucsb-cs156-s25/team02-staff/pull/122"},{"author":{"id":"MDQ6VXNlcjEyNTM2MTg3","is_bot":false,"login":"ameymwalimbe","name":""},"headRefName":"aw-copyUCSBOrgBackend","number":121,"title":"Copied ucsb organization backend crud files into team02","url":"https://github.com/ucsb-cs156-s25/team02-staff/pull/121"}]
